<?php

namespace Training\Helloworld\Rewrite\Model;

class Product extends \Magento\Catalog\Model\Product
{
    /**
     * @return string
     */
    public function getName()
    {
        return parent::getName() . 'Hello world'; // TODO: Change the autogenerated stub
    }
}