
<?php
//foreach($this->getBlocks() as $block):
?>
    <div class="siteblock">
        <div class="block-title">
            <?php
            //    echo $block->getTitle()
            ?></div>
        <div class="block-content">
            <?php
                // echo $block->getContent()
            ?>
        </div>
    </div>

<?php
    // endforeach;
?>

<?php foreach($this->getBlocks() as $block):?>
    <div class="siteblock">
        <div class="block-title"><?php echo $block->getTitle()?></div>
        <div class="block-image">
            <?php if($block->getImage()):?>
                <img src="<?php echo $block->getImageSrc()?>" height="150" width="auto" alt="<?php $block->getTitle()?>" title="<?php $block->getTitle()?>">
            <?php endif;?>
        </div>
        <div class="block-content"><?php echo $block->getContent() ?></div>
    </div>
<?php endforeach;?>
